export type Departament = "PELUQUERIA" | "BIJOUTERIE";
export type ProductType = "UNICO" | "KIT";
export type StockStatus = "in_stock" | "out_of_stock" | "preorder";

export type Product = {
  id: string;
  name: string;
  slug?: string;
  departament?: Departament;
  category?: string;
  price: number;
  old_price?: number | null;
  currency?: string;
  short_description?: string;
  description?: string;
  images?: string[];
  tags?: string[];
  specifications?: Record<string, string>;
  product_type?: ProductType;
  includes?: string[];
  group_id?: string;
  variant_name?: string;
  variants?: Product[];
  is_new?: boolean;
  is_featured?: boolean;
  is_sale?: boolean;
  stock_status?: StockStatus;
  stock_qty?: number | null;
  active?: boolean;
  created_at?: string | null;
  updated_at?: string | null;
  [k: string]: unknown;
};
